version: "3.5"

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 11112222
    ports:
      - "5432:5432"
    volumes:
       - postgres:/data/postgres
    networks:
      - postgres
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: 11112222
    ports:
      - '5050:80'
    volumes:
       - pgadmin:/var/lib/pgadmin
    networks:
      - postgres

volumes:
    postgres:
    pgadmin:
networks:
  postgres:
    driver: bridge