version: "3.8"
services:
  app:
    image: registry.gitlab.com/mad-y4e3/mad-backend:dev
    container_name: travel_tale
    labels:
      - "com.centurylinklabs.watchowner.enable=true"
    environment:
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: travel_tales
      DB_USERNAME: root
      DB_PASSWORD: 11112222
      PASSWORD: 123
      USER: travle-tales
      ACCESS_KEY: AKIAZI2LHJAZQRMNMEVQ
      FILE: files-travel-tales
      PASSWORD_MAIL: idvwgafyizyuvtmx
      POINT_URL: https://files-travel-tales.s3.ap-southeast-2.amazonaws.com
      SECRET_KEY: PWLExSkPWulSxFhecXwnow1zBNkZfppnGOLoK2hq
      USERNAME_MAIL: longlong3578@gmail.com
    ports:
      - '9001:7010'
    networks:
      - hazelcast
networks:
  hazelcast:
    external: true
  