services:
  nginx:
    container_name: nginx
    image: nginx
    ports:
      - '7001:7001'
    restart: unless-stopped
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
    networks:
      - 'server-157'
networks:
  server-157:
    external: true