version: "3.8"

services:

  nginx:
    image: nginx
    container_name: nginx-proxy
    ports:
      - '8000:443'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certs:/etc/ssl/certs
    networks:
      - hazelcast
      
networks:
  hazelcast:
    external: true

