services:
  # zookeeper:
  #   image: bitnami/zookeeper:latest
  #   container_name: zookeeper
  #   ports:
  #     - 2181:2181
  #   environment:
  #     ZOO_SERVER_ID: 1
  #     ZOO_PORT_NUMBER: 2181
  #     ZOO_TICK_TIME: 2000
  #     ALLOW_ANONYMOUS_LOGIN: yes
  #   networks:
  #     - my_network

  # kafka:
  #   depends_on:
  #     - zookeeper
  #   image: bitnami/kafka:latest
  #   container_name: kafka
  #   ports:
  #     - 9092:9092
  #   environment:
  #     KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  #     KAFKA_CFG_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
  #     KAFKA_CFG_TRANSACTION_STATE_LOG_MIN_ISR: 1
  #     KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
  #     KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT_HOST:PLAINTEXT,PLAINTEXT:PLAINTEXT
  #     KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
  #   networks:
  #     - my_network
  kafka:
    restart: unless-stopped
    image: bitnami/kafka:latest
    container_name: kafka
    ports:
      - 80092:9092
    environment: 
      KAFKA_ENABLE_KRAFT: "yes"
      KAFKA_CFG_NODE_ID: 1
      KAFKA_KRAFT_CLUSTER_ID: "loar-tinh"
      KAFKA_CFG_PROCESS_ROLES: "controller,broker"
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: "1@localhost:9093"
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_CFG_LISTENERS: "PLAINTEXT://:9092,CONTROLLER://:9093"
      KAFKA_CFG_ADVERTISED_LISTENERS: "PLAINTEXT://localhost:80092"
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT"
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"
      ALLOW_PLAINTEXT_LISTENER: "yes"
    volumes:
      - kafka:/bitnami/kafka
    networks:
      - my_network
volumes:
   kafka:
    driver: local

networks:
  my_network:
    driver: bridge