version: '3.9'
services:
  mongo_container:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: long
      MONGO_INITDB_ROOT_PASSWORD: long123
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db
    networks:
      - mongo
  mongo_express:
    image: mongo-express:latest
    container_name: mongo_express
    depends_on:
      - mongo_container
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: long
      ME_CONFIG_MONGODB_ADMINPASSWORD: long123
      ME_CONFIG_MONGODB_SERVER: mongo_container
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin123
    ports:
      - 8081:8081
    networks:
      - mongo
volumes:
  mongodb_data:

networks:
  mongo:
    driver: bridge 